greenmail-mail-test/greenmail

- greenmail-core/src/main/java/com/icegreen/greenmail/server/AbstractServer.java
- greenmail-core/src/main/java/com/icegreen/greenmail/util/Service.java
This ensure that cleanup code always gets executed only once, from the calling
thread.
Main thread calls `stopService()`, `quit()`, then `quit()` will get called
again when the thread terminates. On Android this code actually causes
a deadlock since `Thread.join()` does not release the monitor/lock there and `quit()`
never gets called.
This PR also changes the visibility of the `quit()` method since it is
only used internally.
> Don't quit() from within the run() method

- greenmail-core/src/main/java/com/icegreen/greenmail/mail/MovingMessage.java
- greenmail-core/src/test/java/com/icegreen/greenmail/test/SmtpServerTest.java
Per http://tools.ietf.org/html/rfc5321#section-4.5.2:
If the first character is a period and there are other characters on the
line, the first character is deleted.
> Fixes #77: Handle lines with leading periods in SMTP server.

- greenmail-core/src/main/java/com/icegreen/greenmail/base/GreenMailOperations.java
- greenmail-core/src/main/java/com/icegreen/greenmail/configuration/GreenMailConfiguration.java
- greenmail-core/src/main/java/com/icegreen/greenmail/junit/GreenMailRule.java
- greenmail-core/src/main/java/com/icegreen/greenmail/user/UserManager.java
- greenmail-core/src/main/java/com/icegreen/greenmail/util/GreenMail.java
- greenmail-core/src/test/java/com/icegreen/greenmail/examples/ExampleDisableAuthenticationTest.java
- greenmail-core/src/test/java/com/icegreen/greenmail/user/UserManagerTest.java
Added functionality to implement the following:
Allow SMTP/IMAP/POP3 connections using accounts with any password
If an user account doesn't exist when connecting via SMTP/POP3/IMAP - create an account and return an empty mailbox.
> Resolves Issue-59

- greenmail-core/src/main/java/com/icegreen/greenmail/base/GreenMailOperations.java
- greenmail-core/src/main/java/com/icegreen/greenmail/util/GreenMail.java
- greenmail-core/src/main/java/com/icegreen/greenmail/util/GreenMailProxy.java
- greenmail-core/src/test/java/com/icegreen/greenmail/examples/ExampleJavaMailTest.java
- greenmail-core/src/test/java/com/icegreen/greenmail/test/CatchAllTest.java
- greenmail-site/index.html
Deprecated misspelled getReceviedMessagesForDomain method in favor of correctly spelled getReceivedMessagesForDomain in GreenMailOperations interface and its implementing classes.
> Fixes #152 : Misspelled getReceviedMessagesForDomain method

- greenmail-core/src/main/java/com/icegreen/greenmail/store/SimpleMessageAttributes.java
- greenmail-core/src/test/java/com/icegreen/greenmail/examples/ExampleSendTest.java
- greenmail-core/src/test/java/com/icegreen/greenmail/test/specificmessages/SenderRecipientTest.java
When the incoming message doesn't have a Subject header, a NullPointerException is thrown and the rest of the processing fails.
> Handle missing subject headers.

- greenmail-core/src/main/java/com/icegreen/greenmail/store/SimpleMessageAttributes.java
This fixes a TODO in the `FetchCommand` to format the output of the `INTERNALDATE` in a more standard way. I could not find any documentation of this format in any IMAP RFCs, but this format matches python's [`imaplib`](https://docs.python.org/2/library/imaplib.html#imaplib.Time2Internaldate) and is similar to javamail's (but includes the timezone). 
Access to the `SimpleDateFormat` is synchronized because `SimpleDateFormat` is not thread safe, but we could instead create new instances of `SimpleDateFormat` every time we need it.
> FetchCommand: format INTERNALDATE correctly

- greenmail-core/src/main/java/com/icegreen/greenmail/imap/commands/FetchCommand.java
- greenmail-core/src/test/java/com/icegreen/greenmail/imap/commands/ImapProtocolTest.java
Fixes an ArrayIndexOutOfBoundsException thrown when getting a message for an unknown UID in an empty INBOX.
> Fixes ArrayIndexOutOfBoundsException in FetchCommand

- greenmail-core/src/main/java/com/icegreen/greenmail/store/SimpleMessageAttributes.java
- greenmail-core/src/test/java/com/icegreen/greenmail/test/GreenMailUtilTest.java
This is somewhat a breaking change in that invalid email addresses are no longer ignored, but a starting point for discussion.
Using InternetAddress.parse simplifies the parsing of rfc822 addresses so we don't have to pull in additional 3rd party libraries or complicated regex logic to tokenize quotes commas.
> Issue #213: Amended address parsing to handle personal commas

- greenmail-core/src/main/java/com/icegreen/greenmail/util/GreenMailUtil.java
It can be useful to have the method to create multipart for attachment mails public, e.g. for testing parsing of mail attachments.
> made createMultipartWithAttachment public

- greenmail-core/src/main/java/com/icegreen/greenmail/imap/commands/SearchKey.java
- greenmail-core/src/main/java/com/icegreen/greenmail/imap/commands/SearchTermBuilder.java
- greenmail-core/src/main/java/com/icegreen/greenmail/store/StoredMessage.java
- greenmail-core/src/test/java/com/icegreen/greenmail/test/commands/ImapSearchTest.java
Hi there,
this is my pull request for the received date filter implementation as several keywords have not been implemented yet. 5 out of 6 comparison types work, except for LESS THAN:
```
IMAP Line received : <A38 SEARCH OR BEFORE 2-Feb-2010 ON 2-Feb-2010 ALL\r\n>
```
Using less than creates an OR with an ALL statement which currently leads to combine "before" and "on" with an conjunction, effectively dropping the "OR" keyword:
https://github.com/greenmail-mail-test/greenmail/blob/2248d0f1f8b512e370d5762307cba48952e3afaa/greenmail-core/src/main/java/com/icegreen/greenmail/imap/commands/SearchCommandParser.java#L150-L153
As I'm not sure if this is a parsing issue or a search statement creation issue, I'd be happy for some feedback. The not working test is currently commented, but already …
> Implementation of SentDateTerm/ReceivedDateTerm

- greenmail-junit5/pom.xml
- greenmail-junit5/src/main/java/com/icegreen/greenmail/junit5/GreenMailExtension.java
- greenmail-junit5/src/main/java/com/icegreen/greenmail/junit5/package-info.java
- greenmail-junit5/src/test/java/com/icegreen/greenmail/junit5/CustomSetupTests.java
- greenmail-junit5/src/test/java/com/icegreen/greenmail/junit5/DefaultSetupTests.java
- greenmail-junit5/src/test/java/com/icegreen/greenmail/junit5/MultipleSetupsTests.java
- greenmail-junit5/src/test/java/com/icegreen/greenmail/junit5/WithConfigurationTests.java
- greenmail-junit5/src/test/java/resources/log4j.xml
- pom.xml
Related to #219
*Note:* JUnit5 required at least java 8.
If you have any objections then I can publish this extension as separate artifact:
https://github.com/rosolko/greenmail-junit5
> Add junit5 extension module

- greenmail-core/src/main/java/com/icegreen/greenmail/imap/ImapRequestLineReader.java
Hi, I was working with the NGINX Imap Proxy and used greenmail to debug the login.
I just got Timeouts and after doing some digging noticed the command continuation request sould contain some text after the 2 "+", though it very vagely stated in the RFC.
After adding the " Ok" NGINX recognised the request.
> Fixed command continuation request not getting recognised

- greenmail-core/src/main/java/com/icegreen/greenmail/smtp/commands/MailCommand.java
- greenmail-core/src/test/java/com/icegreen/greenmail/test/SmtpServerTest.java
- greenmail-core/src/test/java/com/icegreen/greenmail/test/commands/SMTPCommandTest.java
changed PARAM pattern to extract domain correctly
added tests to check correct extraction by MailCommand
> #291 - MailCommand param pattern too greedy for outlook.com

- greenmail-core/src/main/java/com/icegreen/greenmail/store/SimpleMessageAttributes.java
- greenmail-core/src/test/java/com/icegreen/greenmail/examples/ExampleSendReceiveMessageWithInlineAttachmentTest.java
When retrieving a message with a part with `Content-Disposition: inline` header (so no parameters) from IMAP, the resulting `MimeMessage` will not have a `Content-Disposition` header in that part.
The change done for #113 (6bd221c) will report NIL for the entire Content-Disposition if there are no parameters, instead of NIL for the parameter list. As a result, the `Content-Disposition` is not set in the part. See also RFC 3051 section 9, syntax rule body-fld-dsp.
If possible, I'd love to get this into 1.5.x as well. If you want me to write a pull request to the release/1.5.x branch as well, let me know.
> Fix Content-Disposition: inline not reported without parameters

- README.md
@See also:
https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html
https://de.wikipedia.org/wiki/Javadoc
> Javadoc is the official title of the tool and documentation.

- .gitignore
WIth /*.iml only the files on the first directory is found and not the others
> Fix *.iml in gitignore

- greenmail-junit5/src/main/java/com/icegreen/greenmail/junit5/GreenMailExtension.java
- greenmail-junit5/src/test/java/com/icegreen/greenmail/junit5/AlternateLifecyclesTests.java
I had a use case where I needed GreenMail to be instantiated once per test class instead of once per test method. This behaviour was added to the JUnit5 `GreenMailExtension`. Of course, this change is made backwards compatible so it doesn't affect existing code. The corresponding test class `com.icegreen.greenmail.junit5.AlternateLifecyclesTests` shows how the lifecycle can be switched, essentially:
``` java
@RegisterExtension
GreenMailExtension greenMail = new GreenMailExtension()
.withPerMethodLifecycle(false)
.withConfiguration(...);
```
The extension works very well, please consider publishing the JUnit5 module to Maven Central.
> feat: add the ability to instantiate GreenMail per-class in addition to per-method

- .editorconfig
Adds [editorconfig](https://editorconfig.org/) to help to keep the code formatter like in the readme described.
> Add editorconfig with 4 spaces in general and 2 spaces in xml

- greenmail-core/src/main/java/com/icegreen/greenmail/smtp/commands/AuthCommand.java
The SMTP_SERVER_CONTINUATION constant already contains a space at the end and there is even a comment warning about that next to its definition.
It trips some clients up (Vert.x Mail client in my case) and is not according to spec which says `"334" SP [base64] CRLF` (looking at https://tools.ietf.org/html/rfc4954#ref-SASL).
> Don't include one extra space after 334 response

- greenmail-core/src/main/java/com/icegreen/greenmail/imap/ImapConstants.java
- greenmail-core/src/main/java/com/icegreen/greenmail/imap/commands/IdleCommand.java
- greenmail-core/src/main/java/com/icegreen/greenmail/imap/commands/ImapCommandFactory.java
- greenmail-core/src/test/java/com/icegreen/greenmail/test/ImapServerTest.java
implements naive IDLE support:
* blocks thread after sending continuation request
* sends unsolicited responses for new and expunged messages
#275
Happy about feedback!
> IMAP IDLE support (RFC2177)

- greenmail-core/src/main/java/com/icegreen/greenmail/pop3/Pop3Connection.java
- greenmail-core/src/test/java/com/icegreen/greenmail/test/SendReceiveWithDifferentEncodingsTest.java
In GreenMail, Strings are usually encoded with ISO-8859-1. This was
missing in the Pop3Connection, so Pop3 messages had encoding problems.
This commit also contains a test which demonstrates the problem.
> fix: set correct String encoding in Pop3Connection (fixes #429)

- .gitignore
- greenmail-core/src/main/java/com/icegreen/greenmail/mail/MovingMessage.java
- greenmail-core/src/main/java/com/icegreen/greenmail/smtp/SmtpState.java
- greenmail-core/src/main/java/com/icegreen/greenmail/smtp/auth/AuthenticationState.java
- greenmail-core/src/main/java/com/icegreen/greenmail/smtp/auth/LoginAuthenticationState.java
- greenmail-core/src/main/java/com/icegreen/greenmail/smtp/auth/PlainAuthenticationState.java
- greenmail-core/src/main/java/com/icegreen/greenmail/smtp/auth/UsernameAuthentication.java
- greenmail-core/src/main/java/com/icegreen/greenmail/smtp/commands/AuthCommand.java
- greenmail-core/src/main/java/com/icegreen/greenmail/smtp/commands/MailCommand.java
- greenmail-core/src/main/java/com/icegreen/greenmail/util/GreenMailUtil.java
- greenmail-core/src/test/java/com/icegreen/greenmail/examples/ExampleFindUserByAuthLoginTest.java
Implements #449: Stores the authentication details in the moving message so that it is available in e.g. `MessageDeliveryHandler`. See also the `ExampleFindUserByAuthLoginTest`.
Would be great if you could pick this into the 1.6.x branch, since we can't switch to the new Jakarta namespace quite yet.  I tried cherry picking this commit into the release-1.6.7 tag, there don't seem to be any merge conflicts.
* Since different authentication methods have different details, there's a AuthenticationState base interface with PlainAuthenticationState (with an additional authorizationId) and LoginAuthenticationState POJOs for
the currently supported AUTH mechanisms LOGIN and AUTH. Other AUTH mechanisms may or may not have a username and/or password.
* What I don't fully understand is why the …
> Implements #449 Make authentication details available in MovingMessage

- greenmail-core/src/main/java/com/icegreen/greenmail/imap/commands/CommandParser.java
- greenmail-core/src/test/java/com/icegreen/greenmail/imap/commands/SearchCommandParserTest.java
- greenmail-core/src/test/java/com/icegreen/greenmail/test/commands/ImapSearchTest.java
not the best fix. the spec says flag is an atom. but the same code path is used to parse e.g. UID 1:*. so we would maybe need to provide a way for search keys to specify the type of arguments.
> fix IMAP search keyword parsing

- greenmail-core/src/main/java/com/icegreen/greenmail/configuration/ConfiguredGreenMail.java
- greenmail-core/src/main/java/com/icegreen/greenmail/configuration/GreenMailConfiguration.java
- greenmail-core/src/main/java/com/icegreen/greenmail/configuration/PropertiesBasedGreenMailConfigurationBuilder.java
- greenmail-core/src/main/java/com/icegreen/greenmail/user/UserManager.java
- greenmail-core/src/test/java/com/icegreen/greenmail/SieveDetailHandlingTest.java
- greenmail-core/src/test/java/com/icegreen/greenmail/configuration/PropertiesBasedGreenMailConfigurationBuilderTest.java
Adds support for subaddressing. Can be enabled in the standalone version by adding `-Dgreenmail.sieve.ignore.detail` as suggested in #337 and in unit tests by calling `GreenMailConfiguration#withSieveIgnoreDetail`.
> Implement RFC5233 subaddress handling. Fixes #337

- greenmail-core/src/main/java/com/icegreen/greenmail/util/GreenMail.java
- greenmail-core/src/test/resources/preload/bar@localhost/INBOX/.hidden/test-5.eml
- greenmail-core/src/test/resources/preload/bar@localhost/INBOX/.test-5.eml
> do not preload hidden files and files in hidden folders

- greenmail-core/src/main/java/com/icegreen/greenmail/imap/commands/FetchCommand.java
I faced an issue while testing emails when fetching attachment bodies with base64 encoding. 
Here is my fix for that issue:
> fix: handle input stream body fetch edge case

- greenmail-core/src/main/java/com/icegreen/greenmail/smtp/commands/RcptCommand.java
- greenmail-core/src/test/java/com/icegreen/greenmail/smtp/SMTPCommandTest.java
Hello! I’ve been using GreenMail useful.
While using it, I noticed one area that could be improved, so I’m submitting this PR to address it.
According to [[RFC 2821 Section 4.1.1.3]](https://datatracker.ietf.org/doc/html/rfc2821.html#section-4.1.1.3) mentioned in the Java docs, the RCPT TO command, like the MAIL command, can accept parameters.
However, currently, an error occurs when parameters are added as shown below.
```
issueCommand : "RCPT TO: <test@localhost> NOTIFY=SUCCESS,FAILURE"
expect: "250 OK"
actual : "501 Required syntax: 'RCPT TO:<email@host>'"
```
In my case, I am customizing the SMTPTransport to include custom parameters, but errors occur every time a parameter is added.
I would greatly appreciate it if you could allow changing the regular expression used in the …
>  Modify regex in the RcptCommand class to allow adding parameters.

- greenmail-core/src/main/java/com/icegreen/greenmail/mail/MailAddress.java
- greenmail-core/src/main/java/com/icegreen/greenmail/mail/MovingMessage.java
- greenmail-junit5/src/test/java/com/icegreen/greenmail/junit5/IdenticalRecipientsTests.java
This pull request addresses #856, which was introduced due to duplicate `MimeMessages` showing up when using the `getReceivedMessages()` method when CCs and BCCs are used with the same email destinations.
I originally noticed this when writing various tests to check that CC and BCC properties including multiple destinations were being set correctly in a project I am working on.  
In the method `createTextEmail` in the class `GreenMailUtil`, add any number of CCs or BCCs, and many of the existing tests will fail (a lot check only one message is received at some point).
Ex:
```Java
mimeMessage.setRecipients(Message.RecipientType.CC, to);
mimeMessage.setRecipients(Message.RecipientType.BCC, to);
```
- Switching from List implementation to Set implementation for `MailAddress` in …
> Fix Incoming Message Duplication for Identical Receipients

- greenmail-core/src/main/java/com/icegreen/greenmail/store/SimpleMessageAttributes.java
Addresses in an FETCH response address lists (used for cc, bcc, etc.) should not have spaces in between them. See [RFC3501 formal syntax, `env-cc`](https://datatracker.ietf.org/doc/html/rfc3501#section-9).
Let me know if this code exists for a different reason, or if this behavior is present in other IMAP servers (although I did test one production email server and it sent the address lists without spaces). This was just a minor issue I found while testing an IMAP parser that I wrote. Thanks maintaining for this great project!
> Fix FETCH response envelope address list formatting

- greenmail-core/src/main/java/com/icegreen/greenmail/imap/commands/FetchCommand.java
- greenmail-core/src/test/java/com/icegreen/greenmail/imap/commands/FetchCommandTest.java
When fetching multipart sections with specifiers containing numbers greater than 9 (like 1.10, 1.11, 1.20 etc), always the 1.1 part is returned.
This PR fixes the issue and tests the fix.
The test will fail and reveal the issue in original code, if changes are reverted.
> Wrong parts returned for BODY.PEEK[1.10, 1.11 etc.] 

- pom.xml
When scanning the docker image this CVE is detected due to the transitive dependency created by jersey-media-json-jackson. com.fasterxml.jackson.core should be >= v2.15 to resolve CVE 2025-52999
> add explicit dependency management for the Jackson core modules in pom.xml
